#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/infinix/x6833b

PRODUCT_COPY_FILES += \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.drbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/030c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/030c0000000000000000000000000000.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/85fbf4ccc2fd4a32922a4e90c56179de.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/85fbf4ccc2fd4a32922a4e90c56179de.tabin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/9e412fe49fe460a16bada5a0eeef369f.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/9e412fe49fe460a16bada5a0eeef369f.tabin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/ce4550edbcb1662566b006ebcb303050.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ce4550edbcb1662566b006ebcb303050.tabin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/df1edda8627911e980ae507b9d9a7e7d.tabin \
    vendor/infinix/x6833b/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/infinix/x6833b/proprietary/vendor/data/camera/morpho/morpho_calibration_video.bin:$(TARGET_COPY_OUT_VENDOR)/data/camera/morpho/morpho_calibration_video.bin \
    vendor/infinix/x6833b/proprietary/vendor/data/camera/vidhance/vidhance.lic:$(TARGET_COPY_OUT_VENDOR)/data/camera/vidhance/vidhance.lic \
    vendor/infinix/x6833b/proprietary/vendor/data/camera/vidhance/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/data/camera/vidhance/vidhance_calibration \
    vendor/infinix/x6833b/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/apdb/APDB_MT6789___W2409:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6789___W2409 \
    vendor/infinix/x6833b/proprietary/vendor/etc/apdb/APDB_MT6789___W2409_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6789___W2409_ENUM \
    vendor/infinix/x6833b/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/AudioParamOptions_mgvi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_mgvi.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/preset_default.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_default.bin \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/preset_music.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_music.bin \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/preset_ringtone.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_ringtone.bin \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/preset_voice.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_voice.bin \
    vendor/infinix/x6833b/proprietary/vendor/etc/audio_param/preset_voip.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_voip.bin \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/ecc_list_tran2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_tran2.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/android.hardware.security.keymint-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.trustonic.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.bip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.bip_ap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip_ap.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.gps_pwr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_pwr.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.nxp.nfc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.nxp.nfc.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.thermal_core.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_core.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/tnev.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tnev.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/trustonic.mc_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.mc_kmsetkey_ca.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/vendor.fpsensor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.fpsensor.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/vendor.transsion.hardware.trancam.trancamserver@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.transsion.hardware.trancam.trancamserver@1.0-service.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/infinix/x6833b/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/libnfc-slm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-slm.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/infinix/x6833b/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/disable_skin_control.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_skin_control.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/disable_thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/disable_thermal_temp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal_temp.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/disable_throttling.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_throttling.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/thermal_mtbf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_mtbf.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/thermal_policy_00.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_00.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/thermal_policy_02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_02.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/thermal/thermal_policy_08.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_08.conf \
    vendor/infinix/x6833b/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/infinix/x6833b/proprietary/vendor/etc/wfd_source_capability.csv:$(TARGET_COPY_OUT_VENDOR)/etc/wfd_source_capability.csv \
    vendor/infinix/x6833b/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/infinix/x6833b/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/infinix/x6833b/proprietary/vendor/firmware/aw8624_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_haptic.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/aw8624_osc_rtp_24K_5s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_osc_rtp_24K_5s.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/aw8624_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_lighthouse.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/aw8624_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw8624_rtp_silk.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/infinix/x6833b/proprietary/vendor/firmware/fs1599.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1599.fsm \
    vendor/infinix/x6833b/proprietary/vendor/firmware/fs3001_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fs3001_1.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/fs3001_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fs3001_2.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/fs3001_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fs3001_haptic.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/fs3001_osc_rtp_12K_10s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fs3001_osc_rtp_12K_10s.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6781v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6781v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6785v96.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6785v96.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6785v99.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6785v99.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6853v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6873v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6877v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6877v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6885v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6885v1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v1.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6885v9c.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v9c.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6893v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_90hz6785.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_90hz6785.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_90hz6877.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_90hz6877.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_90hz6885.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_90hz6885.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_cfg_gt9885v1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_gt9885v1.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6781v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6781v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6785a4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6785a4.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6785ae.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6785ae.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6853v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6873v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6877af.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6877af.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6877v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6877v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6885a1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885a1.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6885af.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885af.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6885b0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885b0.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6885b1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885b1.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6885v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9886_firmware_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6893v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6781v01_1080x2280.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6781v01_1080x2300.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6789v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6789v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6833v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6833v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6853v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6855v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6855v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6873v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6877v01_1080x2280.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6877v01_1080x2300.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6879v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6879v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6893v02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v02.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6893v03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v03.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6893v04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v04.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6893v05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v05.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6895v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6895v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_cfg_6983v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6983v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6781v01_1080x2280.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6781v01_1080x2300.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6789v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6789v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6833v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6833v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6853v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6855v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6855v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6873v00.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6873v00.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6877v01_1080x2280.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6877v01_1080x2300.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6879v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6879v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6893v02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v02.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6893v03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v03.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6893v04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v04.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6893v05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v05.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6895v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6895v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/gt9896s_firmware_6983v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6983v01.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/ilitek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ilitek_ts_fw.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mp.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/mp.ini \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6627_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_v1_coeff.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6627_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_v1_patch.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6630_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v1_coeff.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6630_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v1_patch.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6630_fm_v2_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_coeff.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6630_fm_v2_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_coeff_tx.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6630_fm_v2_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_patch.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6630_fm_v2_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_patch_tx.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6632_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6632_fm_v1_coeff.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6632_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6632_fm_v1_patch.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/novatek_ts_fw_144.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_144.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/novatek_ts_fw_jdi.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_jdi.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/novatek_ts_fw_tm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_tm.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/infinix/x6833b/proprietary/vendor/firmware/soc2_2_ram_bt_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1d_1_hdr.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/soc2_2_ram_bt_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1e_1_hdr.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/soc2_2_ram_mcu_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1d_1_hdr.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/soc2_2_ram_mcu_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1e_1_hdr.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/soc2_2_ram_wifi_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1d_1_hdr.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/soc2_2_ram_wifi_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1e_1_hdr.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/soc_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_coeff.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/soc_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_patch.bin \
    vendor/infinix/x6833b/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/infinix/x6833b/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/infinix/x6833b/proprietary/vendor/lib64/hw/android.hardware.camera.provider@2.6-impl-mediatek.solo:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.camera.provider@2.6-impl-mediatek.solo \
    vendor/infinix/x6833b/proprietary/vendor/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/libnfc-nxp_RF.conf

PRODUCT_PACKAGES += \
    AVCSecureVdecCA_510 \
    HEVCSecureVdecCA_510 \
    VP9SecureVdecCA_510 \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    libAVCSecureVencCA_510 \
    libTEECommon \
    libaiselector \
    libbwc \
    libccci_util \
    libgz_gp_client \
    libgz_uree \
    libhevce_sb.ca7.android \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libladder \
    libmtk_drvb \
    libmtkcutils \
    libmtkproperty \
    libmtkrillog \
    libthha \
    libtneclient \
    libtranlog \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libverno \
    libwo \
    arm.graphics-V1-ndk_platform \
    libmtk_drvb \
    vendor.mediatek.hardware.videotelephony@1.0 \
    libHEVCdec_sa.ca7.android \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    librcs_interface \
    librcs_volte_core \
    libvcodec_utility_plat.mt6789 \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvcodec_utility \
    libvcodec_utility_v3a \
    libvcodecdrv \
    libvcodecdrv_v3a \
    libvpudv3a_vcodec \
    vendor.mediatek.hardware.rcs@2.0 \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    fake_serial_yuv_IdxMgr \
    fake_serial_yuv_tuning \
    gc02m1_mipi_raw_IdxMgr \
    gc02m1_mipi_raw_tuning \
    hi1631q_mipi_raw_IdxMgr \
    hi1631q_mipi_raw_tuning \
    hi1634q_mipi_raw_IdxMgr \
    hi1634q_mipi_raw_tuning \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    audio.primary.mediatek \
    audio.r_submix.mediatek \
    fpsensor_fingerprint.default \
    gps.default \
    hwcomposer.mtk_common \
    kmsetkey.trustonic \
    libMcGatekeeper \
    libSoftGatekeeper \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gralloc.common \
    vendor.mediatek.hardware.pq@2.15-impl \
    vulkan.mali \
    sensors.mediatek.V2.0 \
    sound_trigger.primary.mt6789 \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.1-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    lbs_hidl_service-impl \
    lib3a.ae.core \
    lib3a.ae.pipe \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.aishutter.models \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libBasicModule \
    libCamera_fakeserialyuv_E2EHDR_Preview \
    libCamera_fakeserialyuv_E2EHDR_Video \
    libCamera_fakeserialyuv_Face_Capture \
    libCamera_fakeserialyuv_Flash_Capture \
    libCamera_fakeserialyuv_HDR_Capture \
    libCamera_fakeserialyuv_HDR_Preview \
    libCamera_fakeserialyuv_HDR_Reconfig_Preview \
    libCamera_fakeserialyuv_HDR_Reconfig_Video \
    libCamera_fakeserialyuv_HDR_Video \
    libCamera_fakeserialyuv_N3D_Capture \
    libCamera_fakeserialyuv_N3D_Preview \
    libCamera_fakeserialyuv_N3D_Video \
    libCamera_fakeserialyuv_P1_YUV \
    libCamera_fakeserialyuv_Scene_Capture \
    libCamera_fakeserialyuv_Scene_Capture_4cell \
    libCamera_fakeserialyuv_Scene_Preview \
    libCamera_fakeserialyuv_Scene_Preview_4k \
    libCamera_fakeserialyuv_Scene_Preview_ZSD_Flash \
    libCamera_fakeserialyuv_Video_1080 \
    libCamera_fakeserialyuv_Video_4k \
    libCamera_gc02m1mipiraw_Scene_Capture \
    libCamera_gc02m1mipiraw_Scene_Preview \
    libCamera_hi1631qmipiraw_360HDR \
    libCamera_hi1631qmipiraw_3rd_Capture \
    libCamera_hi1631qmipiraw_3rd_Capture_FD \
    libCamera_hi1631qmipiraw_3rd_Preview \
    libCamera_hi1631qmipiraw_3rd_Preview_FD \
    libCamera_hi1631qmipiraw_Boken_Capture \
    libCamera_hi1631qmipiraw_Capture_Zoom1 \
    libCamera_hi1631qmipiraw_Capture_Zoom2 \
    libCamera_hi1631qmipiraw_Default_Capture \
    libCamera_hi1631qmipiraw_Default_Preview \
    libCamera_hi1631qmipiraw_Default_Video \
    libCamera_hi1631qmipiraw_FaceBeauty \
    libCamera_hi1631qmipiraw_FaceBeauty_Preview \
    libCamera_hi1631qmipiraw_FilmVideo \
    libCamera_hi1631qmipiraw_Film_Capture \
    libCamera_hi1631qmipiraw_Flash_Capture \
    libCamera_hi1631qmipiraw_HDR_MINUS_EV \
    libCamera_hi1631qmipiraw_NHDR_0EV \
    libCamera_hi1631qmipiraw_Preview_Zoom1 \
    libCamera_hi1631qmipiraw_Preview_Zoom2 \
    libCamera_hi1631qmipiraw_Resolution \
    libCamera_hi1631qmipiraw_Resolution_Preview \
    libCamera_hi1631qmipiraw_Resolution_zoom \
    libCamera_hi1631qmipiraw_Scene_Capture \
    libCamera_hi1631qmipiraw_Scene_Capture_4cell \
    libCamera_hi1631qmipiraw_Scene_EIS_Video \
    libCamera_hi1631qmipiraw_Scene_Preview \
    libCamera_hi1631qmipiraw_ShortVideo \
    libCamera_hi1631qmipiraw_SuperFlashLight_Capture \
    libCamera_hi1631qmipiraw_SuperNight \
    libCamera_hi1631qmipiraw_TimeLapse_video \
    libCamera_hi1631qmipiraw_Video_1080 \
    libCamera_hi1631qmipiraw_Video_1080_60fps \
    libCamera_hi1631qmipiraw_Video_1080_Zoom1 \
    libCamera_hi1631qmipiraw_Video_2k \
    libCamera_hi1631qmipiraw_Video_2k_Zoom1 \
    libCamera_hi1631qmipiraw_Video_720 \
    libCamera_hi1631qmipiraw_Video_720_Zoom1 \
    libCamera_hi1634qmipiraw_360HDR \
    libCamera_hi1634qmipiraw_3rd_Capture \
    libCamera_hi1634qmipiraw_3rd_Capture_FD \
    libCamera_hi1634qmipiraw_3rd_Preview \
    libCamera_hi1634qmipiraw_3rd_Preview_FD \
    libCamera_hi1634qmipiraw_Boken_Capture \
    libCamera_hi1634qmipiraw_Capture_Zoom1 \
    libCamera_hi1634qmipiraw_Capture_Zoom2 \
    libCamera_hi1634qmipiraw_Default_Capture \
    libCamera_hi1634qmipiraw_Default_Preview \
    libCamera_hi1634qmipiraw_Default_Video \
    libCamera_hi1634qmipiraw_FaceBeauty \
    libCamera_hi1634qmipiraw_FaceBeauty_Preview \
    libCamera_hi1634qmipiraw_FilmVideo \
    libCamera_hi1634qmipiraw_Flash_Capture \
    libCamera_hi1634qmipiraw_G99_Film_Capture \
    libCamera_hi1634qmipiraw_HDR_MINUS_EV \
    libCamera_hi1634qmipiraw_MT_Capture \
    libCamera_hi1634qmipiraw_MT_Preview \
    libCamera_hi1634qmipiraw_NHDR_0EV \
    libCamera_hi1634qmipiraw_Preview_Zoom1 \
    libCamera_hi1634qmipiraw_Preview_Zoom2 \
    libCamera_hi1634qmipiraw_Resolution \
    libCamera_hi1634qmipiraw_Resolution_Preview \
    libCamera_hi1634qmipiraw_Resolution_zoom \
    libCamera_hi1634qmipiraw_Scene_Capture \
    libCamera_hi1634qmipiraw_Scene_Capture_4cell \
    libCamera_hi1634qmipiraw_Scene_EIS_Video \
    libCamera_hi1634qmipiraw_Scene_Preview \
    libCamera_hi1634qmipiraw_ShortVideo \
    libCamera_hi1634qmipiraw_SuperNight \
    libCamera_hi1634qmipiraw_Super_Flash_Screen \
    libCamera_hi1634qmipiraw_Super_Flash_ScreenTorch \
    libCamera_hi1634qmipiraw_Super_Flash_torch \
    libCamera_hi1634qmipiraw_TimeLapse_video \
    libCamera_hi1634qmipiraw_Video_1080 \
    libCamera_hi1634qmipiraw_Video_1080_60fps \
    libCamera_hi1634qmipiraw_Video_1080_Zoom1 \
    libCamera_hi1634qmipiraw_Video_2k \
    libCamera_hi1634qmipiraw_Video_2k_Zoom1 \
    libCamera_hi1634qmipiraw_Video_720 \
    libCamera_hi1634qmipiraw_Video_720_Zoom1 \
    libCamera_ov64b40mipiraw_360HDR \
    libCamera_ov64b40mipiraw_3rd_Capture \
    libCamera_ov64b40mipiraw_3rd_Capture_FD \
    libCamera_ov64b40mipiraw_3rd_Preview \
    libCamera_ov64b40mipiraw_3rd_Preview_FD \
    libCamera_ov64b40mipiraw_Boken_Capture \
    libCamera_ov64b40mipiraw_Capture_Zoom1 \
    libCamera_ov64b40mipiraw_Capture_Zoom2 \
    libCamera_ov64b40mipiraw_FD_Capture_4cell \
    libCamera_ov64b40mipiraw_FD_Capture_Zoom1 \
    libCamera_ov64b40mipiraw_FD_Capture_Zoom2 \
    libCamera_ov64b40mipiraw_Facebeauty_Capture \
    libCamera_ov64b40mipiraw_Film_Capture \
    libCamera_ov64b40mipiraw_Flash_Capture \
    libCamera_ov64b40mipiraw_MagicSky_Capture \
    libCamera_ov64b40mipiraw_NHDR_0EV \
    libCamera_ov64b40mipiraw_Preview_Zoom1 \
    libCamera_ov64b40mipiraw_Preview_Zoom2 \
    libCamera_ov64b40mipiraw_Pro_Capture \
    libCamera_ov64b40mipiraw_Pro_scene \
    libCamera_ov64b40mipiraw_Remosaic_Zoom1 \
    libCamera_ov64b40mipiraw_Remosaic_Zoom2 \
    libCamera_ov64b40mipiraw_Resolution \
    libCamera_ov64b40mipiraw_Resolution_mfnr \
    libCamera_ov64b40mipiraw_Resolution_mfnr_2x \
    libCamera_ov64b40mipiraw_Resolution_mfnr_5x \
    libCamera_ov64b40mipiraw_Resolution_zoom \
    libCamera_ov64b40mipiraw_Scene_Capture \
    libCamera_ov64b40mipiraw_Scene_Capture_4cell \
    libCamera_ov64b40mipiraw_Scene_Capture_Remosaic \
    libCamera_ov64b40mipiraw_Scene_PreFlash_Preview \
    libCamera_ov64b40mipiraw_Scene_Preview \
    libCamera_ov64b40mipiraw_SuperNight \
    libCamera_ov64b40mipiraw_Video \
    libCamera_ov64b40mipiraw_Video_1080p \
    libCamera_ov64b40mipiraw_Video_120fps \
    libCamera_ov64b40mipiraw_Video_240fps \
    libCamera_ov64b40mipiraw_Video_2k \
    libCamera_ov64b40mipiraw_Video_EIS \
    libCamera_ov64b40mipiraw_Video_Zoom1 \
    libCamera_ov64b40mipiraw_Video_Zoom2 \
    libCamera_pblcgc02m1mipiraw_Scene_Capture \
    libCamera_pblcgc02m1mipiraw_Scene_Preview \
    libCamera_pblchi1631qmipiraw_360HDR \
    libCamera_pblchi1631qmipiraw_3rd_Capture \
    libCamera_pblchi1631qmipiraw_3rd_Capture_FD \
    libCamera_pblchi1631qmipiraw_3rd_Preview \
    libCamera_pblchi1631qmipiraw_3rd_Preview_FD \
    libCamera_pblchi1631qmipiraw_Boken_Capture \
    libCamera_pblchi1631qmipiraw_Capture_Zoom1 \
    libCamera_pblchi1631qmipiraw_Capture_Zoom2 \
    libCamera_pblchi1631qmipiraw_Default_Capture \
    libCamera_pblchi1631qmipiraw_Default_Preview \
    libCamera_pblchi1631qmipiraw_Default_Video \
    libCamera_pblchi1631qmipiraw_FaceBeauty \
    libCamera_pblchi1631qmipiraw_FaceBeauty_Preview \
    libCamera_pblchi1631qmipiraw_FilmVideo \
    libCamera_pblchi1631qmipiraw_Film_Capture \
    libCamera_pblchi1631qmipiraw_Flash_Capture \
    libCamera_pblchi1631qmipiraw_HDR_MINUS_EV \
    libCamera_pblchi1631qmipiraw_NHDR_0EV \
    libCamera_pblchi1631qmipiraw_Preview_Zoom1 \
    libCamera_pblchi1631qmipiraw_Preview_Zoom2 \
    libCamera_pblchi1631qmipiraw_Resolution \
    libCamera_pblchi1631qmipiraw_Resolution_Preview \
    libCamera_pblchi1631qmipiraw_Resolution_zoom \
    libCamera_pblchi1631qmipiraw_Scene_Capture \
    libCamera_pblchi1631qmipiraw_Scene_Capture_4cell \
    libCamera_pblchi1631qmipiraw_Scene_EIS_Video \
    libCamera_pblchi1631qmipiraw_Scene_Preview \
    libCamera_pblchi1631qmipiraw_ShortVideo \
    libCamera_pblchi1631qmipiraw_SuperFlashLight_Capture \
    libCamera_pblchi1631qmipiraw_SuperNight \
    libCamera_pblchi1631qmipiraw_TimeLapse_video \
    libCamera_pblchi1631qmipiraw_Video_1080 \
    libCamera_pblchi1631qmipiraw_Video_1080_60fps \
    libCamera_pblchi1631qmipiraw_Video_1080_Zoom1 \
    libCamera_pblchi1631qmipiraw_Video_2k \
    libCamera_pblchi1631qmipiraw_Video_2k_Zoom1 \
    libCamera_pblchi1631qmipiraw_Video_720 \
    libCamera_pblchi1631qmipiraw_Video_720_Zoom1 \
    libCamera_pblchi1634qmipiraw_360HDR \
    libCamera_pblchi1634qmipiraw_3rd_Capture \
    libCamera_pblchi1634qmipiraw_3rd_Capture_FD \
    libCamera_pblchi1634qmipiraw_3rd_Preview \
    libCamera_pblchi1634qmipiraw_3rd_Preview_FD \
    libCamera_pblchi1634qmipiraw_Boken_Capture \
    libCamera_pblchi1634qmipiraw_Capture_Zoom1 \
    libCamera_pblchi1634qmipiraw_Capture_Zoom2 \
    libCamera_pblchi1634qmipiraw_Default_Capture \
    libCamera_pblchi1634qmipiraw_Default_Preview \
    libCamera_pblchi1634qmipiraw_Default_Video \
    libCamera_pblchi1634qmipiraw_FaceBeauty \
    libCamera_pblchi1634qmipiraw_FaceBeauty_Preview \
    libCamera_pblchi1634qmipiraw_FilmVideo \
    libCamera_pblchi1634qmipiraw_Flash_Capture \
    libCamera_pblchi1634qmipiraw_G99_Film_Capture \
    libCamera_pblchi1634qmipiraw_HDR_MINUS_EV \
    libCamera_pblchi1634qmipiraw_MT_Capture \
    libCamera_pblchi1634qmipiraw_MT_Preview \
    libCamera_pblchi1634qmipiraw_NHDR_0EV \
    libCamera_pblchi1634qmipiraw_Preview_Zoom1 \
    libCamera_pblchi1634qmipiraw_Preview_Zoom2 \
    libCamera_pblchi1634qmipiraw_Resolution \
    libCamera_pblchi1634qmipiraw_Resolution_Preview \
    libCamera_pblchi1634qmipiraw_Resolution_zoom \
    libCamera_pblchi1634qmipiraw_Scene_Capture \
    libCamera_pblchi1634qmipiraw_Scene_Capture_4cell \
    libCamera_pblchi1634qmipiraw_Scene_EIS_Video \
    libCamera_pblchi1634qmipiraw_Scene_Preview \
    libCamera_pblchi1634qmipiraw_ShortVideo \
    libCamera_pblchi1634qmipiraw_SuperNight \
    libCamera_pblchi1634qmipiraw_Super_Flash_Screen \
    libCamera_pblchi1634qmipiraw_Super_Flash_ScreenTorch \
    libCamera_pblchi1634qmipiraw_Super_Flash_torch \
    libCamera_pblchi1634qmipiraw_TimeLapse_video \
    libCamera_pblchi1634qmipiraw_Video_1080 \
    libCamera_pblchi1634qmipiraw_Video_1080_60fps \
    libCamera_pblchi1634qmipiraw_Video_1080_Zoom1 \
    libCamera_pblchi1634qmipiraw_Video_2k \
    libCamera_pblchi1634qmipiraw_Video_2k_Zoom1 \
    libCamera_pblchi1634qmipiraw_Video_720 \
    libCamera_pblchi1634qmipiraw_Video_720_Zoom1 \
    libCamera_pblcov64b40mipiraw_360HDR \
    libCamera_pblcov64b40mipiraw_3rd_Capture \
    libCamera_pblcov64b40mipiraw_3rd_Capture_FD \
    libCamera_pblcov64b40mipiraw_3rd_Preview \
    libCamera_pblcov64b40mipiraw_3rd_Preview_FD \
    libCamera_pblcov64b40mipiraw_Boken_Capture \
    libCamera_pblcov64b40mipiraw_Capture_Zoom1 \
    libCamera_pblcov64b40mipiraw_Capture_Zoom2 \
    libCamera_pblcov64b40mipiraw_FD_Capture_4cell \
    libCamera_pblcov64b40mipiraw_FD_Capture_Zoom1 \
    libCamera_pblcov64b40mipiraw_FD_Capture_Zoom2 \
    libCamera_pblcov64b40mipiraw_Facebeauty_Capture \
    libCamera_pblcov64b40mipiraw_Film_Capture \
    libCamera_pblcov64b40mipiraw_Flash_Capture \
    libCamera_pblcov64b40mipiraw_MagicSky_Capture \
    libCamera_pblcov64b40mipiraw_NHDR_0EV \
    libCamera_pblcov64b40mipiraw_Preview_Zoom1 \
    libCamera_pblcov64b40mipiraw_Preview_Zoom2 \
    libCamera_pblcov64b40mipiraw_Pro_Capture \
    libCamera_pblcov64b40mipiraw_Pro_scene \
    libCamera_pblcov64b40mipiraw_Remosaic_Zoom1 \
    libCamera_pblcov64b40mipiraw_Remosaic_Zoom2 \
    libCamera_pblcov64b40mipiraw_Resolution \
    libCamera_pblcov64b40mipiraw_Resolution_mfnr \
    libCamera_pblcov64b40mipiraw_Resolution_mfnr_2x \
    libCamera_pblcov64b40mipiraw_Resolution_mfnr_5x \
    libCamera_pblcov64b40mipiraw_Resolution_zoom \
    libCamera_pblcov64b40mipiraw_Scene_Capture \
    libCamera_pblcov64b40mipiraw_Scene_Capture_4cell \
    libCamera_pblcov64b40mipiraw_Scene_Capture_Remosaic \
    libCamera_pblcov64b40mipiraw_Scene_PreFlash_Preview \
    libCamera_pblcov64b40mipiraw_Scene_Preview \
    libCamera_pblcov64b40mipiraw_SuperNight \
    libCamera_pblcov64b40mipiraw_Video \
    libCamera_pblcov64b40mipiraw_Video_1080p \
    libCamera_pblcov64b40mipiraw_Video_120fps \
    libCamera_pblcov64b40mipiraw_Video_240fps \
    libCamera_pblcov64b40mipiraw_Video_2k \
    libCamera_pblcov64b40mipiraw_Video_EIS \
    libCamera_pblcov64b40mipiraw_Video_Zoom1 \
    libCamera_pblcov64b40mipiraw_Video_Zoom2 \
    libCamera_pbrogc02m1mipiraw_Scene_Capture \
    libCamera_pbrogc02m1mipiraw_Scene_Preview \
    libCamera_pbrohi1631qmipiraw_360HDR \
    libCamera_pbrohi1631qmipiraw_3rd_Capture \
    libCamera_pbrohi1631qmipiraw_3rd_Capture_FD \
    libCamera_pbrohi1631qmipiraw_3rd_Preview \
    libCamera_pbrohi1631qmipiraw_3rd_Preview_FD \
    libCamera_pbrohi1631qmipiraw_Boken_Capture \
    libCamera_pbrohi1631qmipiraw_Capture_Zoom1 \
    libCamera_pbrohi1631qmipiraw_Capture_Zoom2 \
    libCamera_pbrohi1631qmipiraw_Default_Capture \
    libCamera_pbrohi1631qmipiraw_Default_Preview \
    libCamera_pbrohi1631qmipiraw_Default_Video \
    libCamera_pbrohi1631qmipiraw_FaceBeauty \
    libCamera_pbrohi1631qmipiraw_FaceBeauty_Preview \
    libCamera_pbrohi1631qmipiraw_FilmVideo \
    libCamera_pbrohi1631qmipiraw_Film_Capture \
    libCamera_pbrohi1631qmipiraw_Flash_Capture \
    libCamera_pbrohi1631qmipiraw_HDR_MINUS_EV \
    libCamera_pbrohi1631qmipiraw_NHDR_0EV \
    libCamera_pbrohi1631qmipiraw_Preview_Zoom1 \
    libCamera_pbrohi1631qmipiraw_Preview_Zoom2 \
    libCamera_pbrohi1631qmipiraw_Resolution \
    libCamera_pbrohi1631qmipiraw_Resolution_Preview \
    libCamera_pbrohi1631qmipiraw_Resolution_zoom \
    libCamera_pbrohi1631qmipiraw_Scene_Capture \
    libCamera_pbrohi1631qmipiraw_Scene_Capture_4cell \
    libCamera_pbrohi1631qmipiraw_Scene_EIS_Video \
    libCamera_pbrohi1631qmipiraw_Scene_Preview \
    libCamera_pbrohi1631qmipiraw_ShortVideo \
    libCamera_pbrohi1631qmipiraw_SuperFlashLight_Capture \
    libCamera_pbrohi1631qmipiraw_SuperNight \
    libCamera_pbrohi1631qmipiraw_TimeLapse_video \
    libCamera_pbrohi1631qmipiraw_Video_1080 \
    libCamera_pbrohi1631qmipiraw_Video_1080_60fps \
    libCamera_pbrohi1631qmipiraw_Video_1080_Zoom1 \
    libCamera_pbrohi1631qmipiraw_Video_2k \
    libCamera_pbrohi1631qmipiraw_Video_2k_Zoom1 \
    libCamera_pbrohi1631qmipiraw_Video_720 \
    libCamera_pbrohi1631qmipiraw_Video_720_Zoom1 \
    libCamera_pbrohi1634qmipiraw_360HDR \
    libCamera_pbrohi1634qmipiraw_3rd_Capture \
    libCamera_pbrohi1634qmipiraw_3rd_Capture_FD \
    libCamera_pbrohi1634qmipiraw_3rd_Preview \
    libCamera_pbrohi1634qmipiraw_3rd_Preview_FD \
    libCamera_pbrohi1634qmipiraw_Boken_Capture \
    libCamera_pbrohi1634qmipiraw_Capture_Zoom1 \
    libCamera_pbrohi1634qmipiraw_Capture_Zoom2 \
    libCamera_pbrohi1634qmipiraw_Default_Capture \
    libCamera_pbrohi1634qmipiraw_Default_Preview \
    libCamera_pbrohi1634qmipiraw_Default_Video \
    libCamera_pbrohi1634qmipiraw_FaceBeauty \
    libCamera_pbrohi1634qmipiraw_FaceBeauty_Preview \
    libCamera_pbrohi1634qmipiraw_FilmVideo \
    libCamera_pbrohi1634qmipiraw_Flash_Capture \
    libCamera_pbrohi1634qmipiraw_G99_Film_Capture \
    libCamera_pbrohi1634qmipiraw_HDR_MINUS_EV \
    libCamera_pbrohi1634qmipiraw_MT_Capture \
    libCamera_pbrohi1634qmipiraw_MT_Preview \
    libCamera_pbrohi1634qmipiraw_NHDR_0EV \
    libCamera_pbrohi1634qmipiraw_Preview_Zoom1 \
    libCamera_pbrohi1634qmipiraw_Preview_Zoom2 \
    libCamera_pbrohi1634qmipiraw_Resolution \
    libCamera_pbrohi1634qmipiraw_Resolution_Preview \
    libCamera_pbrohi1634qmipiraw_Resolution_zoom \
    libCamera_pbrohi1634qmipiraw_Scene_Capture \
    libCamera_pbrohi1634qmipiraw_Scene_Capture_4cell \
    libCamera_pbrohi1634qmipiraw_Scene_EIS_Video \
    libCamera_pbrohi1634qmipiraw_Scene_Preview \
    libCamera_pbrohi1634qmipiraw_ShortVideo \
    libCamera_pbrohi1634qmipiraw_SuperNight \
    libCamera_pbrohi1634qmipiraw_Super_Flash_Screen \
    libCamera_pbrohi1634qmipiraw_Super_Flash_ScreenTorch \
    libCamera_pbrohi1634qmipiraw_Super_Flash_torch \
    libCamera_pbrohi1634qmipiraw_TimeLapse_video \
    libCamera_pbrohi1634qmipiraw_Video_1080 \
    libCamera_pbrohi1634qmipiraw_Video_1080_60fps \
    libCamera_pbrohi1634qmipiraw_Video_1080_Zoom1 \
    libCamera_pbrohi1634qmipiraw_Video_2k \
    libCamera_pbrohi1634qmipiraw_Video_2k_Zoom1 \
    libCamera_pbrohi1634qmipiraw_Video_720 \
    libCamera_pbrohi1634qmipiraw_Video_720_Zoom1 \
    libCamera_pbroov64b40mipiraw_360HDR \
    libCamera_pbroov64b40mipiraw_3rd_Capture \
    libCamera_pbroov64b40mipiraw_3rd_Capture_FD \
    libCamera_pbroov64b40mipiraw_3rd_Preview \
    libCamera_pbroov64b40mipiraw_3rd_Preview_FD \
    libCamera_pbroov64b40mipiraw_Boken_Capture \
    libCamera_pbroov64b40mipiraw_Capture_Zoom1 \
    libCamera_pbroov64b40mipiraw_Capture_Zoom2 \
    libCamera_pbroov64b40mipiraw_FD_Capture_4cell \
    libCamera_pbroov64b40mipiraw_FD_Capture_Zoom1 \
    libCamera_pbroov64b40mipiraw_FD_Capture_Zoom2 \
    libCamera_pbroov64b40mipiraw_Facebeauty_Capture \
    libCamera_pbroov64b40mipiraw_Film_Capture \
    libCamera_pbroov64b40mipiraw_Flash_Capture \
    libCamera_pbroov64b40mipiraw_MagicSky_Capture \
    libCamera_pbroov64b40mipiraw_NHDR_0EV \
    libCamera_pbroov64b40mipiraw_Preview_Zoom1 \
    libCamera_pbroov64b40mipiraw_Preview_Zoom2 \
    libCamera_pbroov64b40mipiraw_Pro_Capture \
    libCamera_pbroov64b40mipiraw_Pro_scene \
    libCamera_pbroov64b40mipiraw_Remosaic_Zoom1 \
    libCamera_pbroov64b40mipiraw_Remosaic_Zoom2 \
    libCamera_pbroov64b40mipiraw_Resolution \
    libCamera_pbroov64b40mipiraw_Resolution_mfnr \
    libCamera_pbroov64b40mipiraw_Resolution_mfnr_2x \
    libCamera_pbroov64b40mipiraw_Resolution_mfnr_5x \
    libCamera_pbroov64b40mipiraw_Resolution_zoom \
    libCamera_pbroov64b40mipiraw_Scene_Capture \
    libCamera_pbroov64b40mipiraw_Scene_Capture_4cell \
    libCamera_pbroov64b40mipiraw_Scene_Capture_Remosaic \
    libCamera_pbroov64b40mipiraw_Scene_PreFlash_Preview \
    libCamera_pbroov64b40mipiraw_Scene_Preview \
    libCamera_pbroov64b40mipiraw_SuperNight \
    libCamera_pbroov64b40mipiraw_Video \
    libCamera_pbroov64b40mipiraw_Video_1080p \
    libCamera_pbroov64b40mipiraw_Video_120fps \
    libCamera_pbroov64b40mipiraw_Video_240fps \
    libCamera_pbroov64b40mipiraw_Video_2k \
    libCamera_pbroov64b40mipiraw_Video_EIS \
    libCamera_pbroov64b40mipiraw_Video_Zoom1 \
    libCamera_pbroov64b40mipiraw_Video_Zoom2 \
    libDefaultFpsActor \
    libFrameRecord \
    libImageEval \
    libJpgEncPipe \
    libMcClient \
    libMtkSpeechEnh \
    libNoFpsActor \
    libNvLutEffect \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libTranASD \
    libTranArcFilter \
    libTranArcFlashNew \
    libTranArcHDR \
    libTranArcLLHDR \
    libTranArcLowLight \
    libTranArcNightHawk \
    libTranAutoColorLevel \
    libTranBefMakeup \
    libTranColorEnhance \
    libTranDenoise \
    libTranExtImgProc \
    libTranExtImgThread \
    libTranEyeDetect \
    libTranGenderDetect \
    libTranHumanLight \
    libTranITDFaceBeauty \
    libTranMSFilter \
    libTranMagicSky \
    libTranMegDualDepth \
    libTranMegDualDepthtoBokeh \
    libTranMegDualRefocus \
    libTranPlatHW \
    libTranSTPRRepair \
    libTranSTSingleBlur \
    libTranSlimBody \
    libTranSmartDetection \
    libTranSuperResolution \
    libTranVideoFilter \
    libTranVideoLuminousEffects \
    libTran_Log \
    libTran_mtkPowerAPI \
    libWaterMarkProc \
    lib_iir \
    lib_speech_enh \
    lib_sr_indep_ocl \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaiawb_moon \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaibc_tuning_p4 \
    libaidepth_tuning \
    libaipe_bokeh \
    libalsautils-v31 \
    libamipengine \
    libanc_dc_base \
    libanc_hdr \
    libanc_hdr_adapter_hi1631q_17201701_front_g97 \
    libanc_hdr_adapter_hi1634q_17201821_front_g97 \
    libanc_hdr_adapter_ov64b40_17201840_back_g97 \
    libancbase \
    libancbase_848 \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_low_light_shot \
    libarcsoft_night_hawk \
    libarcsoft_torch_portrait_night \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libasn1c_core \
    libasn1c_mapi \
    libasn1c_mdmi \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libc++_shared \
    libcalculatesharpness \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.seninfn3d \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam3_tranelapsedtime \
    libcam3_tranpriorityctrl \
    libcam3_transerverengine \
    libcam3atms_profiles \
    libcam_STcallbackHelper_utils \
    libcamalgo.3dnr \
    libcamalgo.WarpMapResizer \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.hdr10p \
    libcamalgo.ispfeature \
    libcamalgo.lmv \
    libcamalgo.lsc \
    libcamalgo.mcnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.utility \
    libcamalgo.vsdofUtil \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libcares_naptr \
    libcarrierconfig \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcolorenhance_64 \
    libcolorlevel \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libcvsd_mtk \
    libdecrypt \
    libdenoise \
    libdip_drv \
    libdip_postproc \
    libdre \
    libeffect_hal \
    libeffecthal.base \
    libeyedetector \
    libfacesattribute \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libfgauge_gm30 \
    libfile_op \
    libforkexecwrap \
    libformatter \
    libfp_ext_svc2 \
    libfsmaudio \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgwsd-ril \
    libgwsdv2-ril \
    libgwsdv3-ril \
    libheichal \
    libhfmanager \
    libhfmanagerwrapper \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libimgsensorca \
    libimsg_log \
    libispcameraca \
    libitdfacebeauty \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkmsetkey \
    libksensor \
    liblpcnr \
    libmagicsky_64 \
    libminizip \
    libmipc \
    libmmagent \
    libmml \
    libmnetlink_v104 \
    libmorpho_video_stabilizer \
    libmpbase \
    libmsbc_mtk \
    libmsnr \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkares \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_3rdparty.thread \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdWarpConvert \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtkisp_metadata_v2 \
    libmtklimiter_vendor \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtkshifter_vendor \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libmvpu_cic_ci_compiler \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_engine \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_pub \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libneuron_graph_delegate.mtk \
    libneuron_platform \
    libnir_neon_driver_ndk.mtk.vndk \
    libnpagent \
    libnpagent_server \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    liboemcrypto \
    libpn557_fw \
    libportrait_repair_ppl3_ocl \
    libpower_timer \
    libpqframework \
    libratconfig \
    libremosaic_wrapper \
    librgbwlightsensor \
    librilfusion \
    librpc \
    librt_extamp_intf \
    libsdk_sr \
    libsegmention \
    libsegmentionPre \
    libskhynix_q2b_shared \
    libsmartdetector \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libst_mobile \
    libst_sr_models \
    libstblur_capture_api \
    libstereoinfoaccessor_vsdof \
    libstorage_otp \
    libsysenv \
    libtf_asd_lib \
    libtflite_mtk \
    libtflite_native_gainference \
    libtflite_native_inference \
    libtflite_native_seginference \
    libtlcWidevineModularDrm \
    libtnev \
    libtrancamJsonConvertor \
    libtrancam_filelockmgr \
    libtranssion_bodybeauty \
    libtranssion_cal \
    libtrm \
    libudf \
    liburee_meta_drmkeyinstall \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libvideofilmeffect \
    libvideofilter_cl_64 \
    libvow_ap_test_aa \
    libvow_ap_test_dd \
    libvow_ap_test_ha \
    libvow_ap_test_hh \
    libvow_ap_test_nn \
    libvpu \
    libvpu5 \
    libwa_depth \
    libwa_dof \
    libwa_refocus \
    libwa_rtdof \
    libwifi-hal-mtk \
    libwpfa \
    libwvhidl \
    libwvdrmengine \
    libDR \
    libaal_cust_func \
    libaalservice \
    libaiselector \
    libdpframework \
    libmnl \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libneuron_runtime.5 \
    libnir_neon_driver \
    libpq_cust_base \
    libpq_prot \
    libpqparamparser \
    libmtkcam_streaminfo_plugin-p1stt \
    ov64b40_mipi_raw_IdxMgr \
    ov64b40_mipi_raw_tuning \
    pblcgc02m1_mipi_raw_IdxMgr \
    pblcgc02m1_mipi_raw_tuning \
    pblchi1631q_mipi_raw_IdxMgr \
    pblchi1631q_mipi_raw_tuning \
    pblchi1634q_mipi_raw_IdxMgr \
    pblchi1634q_mipi_raw_tuning \
    pblcov64b40_mipi_raw_IdxMgr \
    pblcov64b40_mipi_raw_tuning \
    pbrogc02m1_mipi_raw_IdxMgr \
    pbrogc02m1_mipi_raw_tuning \
    pbrohi1631q_mipi_raw_IdxMgr \
    pbrohi1631q_mipi_raw_tuning \
    pbrohi1634q_mipi_raw_IdxMgr \
    pbrohi1634q_mipi_raw_tuning \
    pbroov64b40_mipi_raw_IdxMgr \
    pbroov64b40_mipi_raw_tuning \
    s5k2lqsx_mipi_raw_IdxMgr \
    s5k4h7_mipi_raw_IdxMgr \
    vendor.fpsensor.hardware.fpsensorhidlsvc@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.transsion.hardware.tne.tneengine@1.0 \
    vendor.transsion.hardware.trancam.trancamserver@1.0 \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    TranssionCamera \
    android.hardware.biometrics.fingerprint@2.1-service.xml \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.keymint-service.trustonic.xml \
    android.hardware.security.secureclock-service.trustonic.xml \
    android.hardware.security.sharedsecret-service.trustonic.xml \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_apuware_apusys.xml \
    manifest_apuware_hmp.xml \
    manifest_apuware_utils.xml \
    manifest_cameraprovider.xml \
    manifest_hwcomposer.xml \
    manifest_media_c2_V1_2_default.xml \
    vendor.transsion.hardware.trancam.trancamserver@1.0.xml \
    ccci_mdinit \
    ccci_rpcd \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.security.keymint-service.trustonic \
    camerahalserver \
    android.hardware.graphics.allocator@4.0-service-mediatek.mt6789 \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.tne@1.0-service \
    vendor.transsion.hardware.trancam.trancamserver@1.0-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    kmsetkey_ca.trustonic \
    mcDriverDaemon \
    mnld \
    v3avpud.mt6789 \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    rcs_volte_stack \
    thermal_core \
    volte_clientapi_ua \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_rcs_ua \
    volte_stack \
    volte_ua \
    wlan_assistant \
    wmt_launcher \
    wmt_loader

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_graphics_allocator@4_0-service-mediatek \
    vendor_bin_v3avpud \
    vendor_lib_arm_graphics-V1-ndk_platform_so \
    vendor_lib_libmtk_drvb_so \
    vendor_lib_libvcodec_utility_so \
    vendor_lib_libvcodec_utility_v3a_so \
    vendor_lib_libvcodecdrv_so \
    vendor_lib_libvcodecdrv_v3a_so \
    vendor_lib_libvpudv3a_vcodec_so \
    vendor_lib64_egl_libGLES_mali_so \
    vendor_lib64_hw_audio_primary_mt6789_so \
    vendor_lib64_hw_audio_r_submix_mt6789_so \
    vendor_lib64_hw_kmsetkey_default_so \
    vendor_lib64_hw_gatekeeper_trustonic_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_hw_android_hardware_graphics_allocator@4_0-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib64_hw_gralloc_common_so \
    vendor_lib64_hw_vendor_mediatek_hardware_pq@2_15-impl_so \
    vendor_lib64_hw_vulkan_mali_so \
    vendor_lib64_hw_sensors_mt6789_so \
    vendor_lib64_arm_graphics-V1-ndk_platform_so \
    vendor_lib64_libDR_so \
    vendor_lib64_libaal_cust_func_so \
    vendor_lib64_libaalservice_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libmnl_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libneuralnetworks_sl_driver_mtk_prebuilt_so \
    vendor_lib64_libneuron_adapter_mgvi_so \
    vendor_lib64_libneuron_runtime_5_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_cust_base_so \
    vendor_lib64_libpq_prot_so \
    vendor_lib64_libpqparamparser_so
